server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nap_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        file:C:\\Users\\***\\Desktop\\Nap_Blog\\upload\\avatar\\,file:C:\\Users\\***\\Desktop\\Nap_Blog\\upload\\
  mail:
    username: ***@gmail.com
    password: ***
    host: smtp.gmail.com
  data:
    redis:
      host: localhost
      port: 6379
mybatis-plus:
  configuration:
    #??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
#邮件格式模板
email:
  from: ***@gmail.com
  subject:
    defaultCommentSubject: 标题:《%s》有新评论
    replyCommentSubject: 你在nap博客评论的标题为:《%s》的文章有回复
    VerificationCodeSubject: 博客验证码
  content:
    defaultCommentContent: |
      文章标题:%s<br>
      昵称:%s<br>
      评论内容:%s<br>
      邮箱:%s<br>
      网址：%s<br>
    replyCommentContent: |
      文章标题:%s<br>
      昵称:%s<br>
      回复你说:%s<br>
      博客网址：http://localhost:3000/
    parentCommentContent: |
      文章标题:%s<br>
      昵称:%s<br>
      有回复说:%s<br>
      博客网址：http://localhost:3000/
   


